'use client'
import { useState, useEffect } from 'react'
import { getStoredUser, getCompany, updateCompany, getIndustryTemplates, updateMe, type Company, type User } from '@/lib/api'
import { Key, Phone, Bot, User as UserIcon, Building2, Brain, MessageCircle, Sparkles, Calendar, CheckCircle2, X, AlertCircle, ShieldCheck } from 'lucide-react'
import clsx from 'clsx'

function Section({ title, icon: Icon, children, description }: {
  title: string; icon: React.ElementType; children: React.ReactNode; description?: string
}) {
  return (
    <div className="card p-5 md:p-6 shadow-sm border-gray-100">
      <div className="flex items-start gap-3 mb-5">
        <div className="w-10 h-10 rounded-lg bg-brand-50 flex items-center justify-center shrink-0">
          <Icon size={20} className="text-brand-600" />
        </div>
        <div>
          <h2 className="font-bold text-gray-900">{title}</h2>
          {description && <p className="text-xs text-gray-500 mt-0.5 font-medium">{description}</p>}
        </div>
      </div>
      {children}
    </div>
  )
}

function EnvRow({ label, envKey, description }: { label: string; envKey: string; description: string }) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-start justify-between py-3 border-b border-gray-100 last:border-0 gap-2">
      <div>
        <p className="text-sm font-medium text-gray-800">{label}</p>
        <p className="text-[11px] text-gray-400 mt-0.5">{description}</p>
      </div>
      <code className="text-[10px] sm:text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded font-mono break-all sm:break-normal">
        {envKey}
      </code>
    </div>
  )
}

export default function SettingsPage() {
  const [user, setUser] = useState<User | null>(null)
  const [company, setCompany] = useState<Company | null>(null)
  const [templates, setTemplates] = useState<Record<string, { industry_lingo: string; company_memory: string }>>({})
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [connecting, setConnecting] = useState(false)

  useEffect(() => {
    setUser(getStoredUser())
    Promise.all([getCompany(), getIndustryTemplates()])
      .then(([c, t]) => {
        setCompany(c)
        setTemplates(t)
      })
      .finally(() => setLoading(false))
  }, [])

  async function handleSave(e: React.FormEvent) {
    e.preventDefault()
    if (!company) return
    setSaving(true)
    try {
      await updateCompany(company)
      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch (err) {
      console.error(err)
      alert('Failed to save settings')
    } finally {
      setSaving(false)
    }
  }

  const updateAI = (field: string, value: string) => {
    if (!company) return
    setCompany({
      ...company,
      ai_config: { ...company.ai_config, [field]: value }
    })
  }

  const handleIndustryChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const industry = e.target.value
    if (!company) return
    
    let newConfig = { ...company.ai_config }
    if (templates[industry]) {
      newConfig.industry_lingo = templates[industry].industry_lingo
      newConfig.company_memory = templates[industry].company_memory
    }
    
    setCompany({
      ...company,
      industry,
      ai_config: newConfig
    })
  }

  const connectWorkCalendar = async () => {
    setConnecting(true)
    try {
      // In a real flow, this would redirect to Okta/OAuth
      // For this implementation, we handle the integration internally as a 'shadow'
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      const updated = await updateMe({ 
        calendar_connected: true,
        // These would normally be generated by the platform's Cal.com integration
        calcom_username: user?.name.toLowerCase().replace(/\s/g, '-'),
        calcom_event_id: 123456 // Internal shadow ID
      })
      setUser(updated)
    } catch (err) {
      alert('Failed to connect work calendar')
    } finally {
      setConnecting(false)
    }
  }

  const disconnectCalendar = async () => {
    if (!confirm('Are you sure you want to disconnect your work calendar? AI will no longer be able to book meetings for you.')) return
    try {
      const updated = await updateMe({ 
        calendar_connected: false, 
        calcom_username: null, 
        calcom_event_id: null 
      })
      setUser(updated)
    } catch (err) {
      alert('Failed to disconnect calendar')
    }
  }

  if (loading) return <div className="text-gray-400 text-sm p-8 font-bold">Loading settings…</div>

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20">
      <div className="mb-6 px-1">
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Settings</h1>
        <p className="text-gray-500 text-sm mt-1 font-medium italic">Configure your profile, AI memory, and communication channels.</p>
      </div>

      <form onSubmit={handleSave} className="space-y-6">
        {/* Account */}
        <Section title="Account" icon={UserIcon} description="Your personal profile information">
          <div className="space-y-2 text-sm">
            <div className="flex justify-between py-2 border-b border-gray-100">
              <span className="text-gray-500 font-medium">Name</span>
              <span className="font-bold text-gray-900">{user?.name}</span>
            </div>
            <div className="flex justify-between py-2 border-b border-gray-100">
              <span className="text-gray-500 font-medium">Email</span>
              <span className="font-bold text-gray-900 truncate ml-4">{user?.email}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-gray-500 font-medium">Role</span>
              <span className="font-bold text-gray-900 capitalize">{user?.role}</span>
            </div>
          </div>
        </Section>

        {/* Calendar Connection */}
        <Section title="Work Calendar" icon={Calendar} description="Enable AI to schedule meetings on your behalf">
          {user?.calendar_connected ? (
            <div className="bg-brand-50 border border-brand-100 rounded-2xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center text-brand-600 shadow-sm border border-brand-50">
                  <ShieldCheck size={24} />
                </div>
                <div>
                  <p className="font-bold text-brand-900 text-sm">Work Calendar Connected</p>
                  <p className="text-[10px] text-brand-600 font-bold uppercase tracking-tight">Syncing via Converso Managed Cal</p>
                </div>
              </div>
              <button 
                type="button"
                onClick={disconnectCalendar}
                className="btn-secondary py-2 px-6 text-xs font-bold text-red-600 border-red-100 hover:bg-red-50 w-full sm:w-auto"
              >
                Disconnect
              </button>
            </div>
          ) : (
            <div className="bg-gray-50 border border-dashed border-gray-200 rounded-2xl p-8 text-center">
              <div className="w-14 h-14 rounded-2xl bg-white flex items-center justify-center mx-auto mb-4 shadow-sm">
                <Calendar size={28} className="text-gray-400" />
              </div>
              <h3 className="font-bold text-gray-900 mb-1">No Work Calendar Integrated</h3>
              <p className="text-xs text-gray-500 mb-6 max-w-sm mx-auto font-medium leading-relaxed">
                Connect your work calendar via Okta to allow the AI to automatically schedule meetings when a lead is ready. We handle the complexity of scheduling for you.
              </p>
              <button 
                type="button"
                onClick={connectWorkCalendar}
                disabled={connecting}
                className="btn-primary px-10 py-3 font-bold text-sm shadow-lg shadow-brand-100 animate-in fade-in zoom-in duration-300"
              >
                {connecting ? 'Connecting to Okta...' : 'Connect Work Calendar'}
              </button>
            </div>
          )}
        </Section>

        {/* Industry Selector */}
        <Section title="Industry Context" icon={Building2} description="Select your industry to autopopulate AI knowledge">
          <div>
            <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Your Industry</label>
            <div className="relative">
              <select 
                className="input pr-10 appearance-none font-bold" 
                value={company?.industry || ''} 
                onChange={handleIndustryChange}
              >
                <option value="">Select an industry...</option>
                {Object.keys(templates).map(name => (
                  <option key={name} value={name}>{name}</option>
                ))}
                <option value="Other">Other (Manual Entry)</option>
              </select>
              <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400">
                <Sparkles size={16} className="text-brand-500" />
              </div>
            </div>
          </div>
        </Section>

        {/* AI Memory & Knowledge */}
        <Section title="AI Memory & Knowledge" icon={Brain} description="Information the AI uses to curate personal responses">
          <div className="space-y-5">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5 flex items-center gap-2">
                <MessageCircle size={12} className="text-brand-500" />
                Industry Lingo
              </label>
              <textarea
                className="input min-h-[100px] resize-none text-sm leading-relaxed font-medium"
                value={company?.ai_config.industry_lingo || ''}
                onChange={e => updateAI('industry_lingo', e.target.value)}
                placeholder="e.g. use terms like 'Pre-approval', 'HELOC', 'Amortization'."
              />
            </div>
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5 flex items-center gap-2">
                <Brain size={12} className="text-brand-500" />
                Company Memory
              </label>
              <textarea
                className="input min-h-[120px] resize-none text-sm leading-relaxed font-medium"
                value={company?.ai_config.company_memory || ''}
                onChange={e => updateAI('company_memory', e.target.value)}
                placeholder="e.g. We specialize in first-time home buyers in Ontario."
              />
            </div>
          </div>
        </Section>

        {/* AI Behaviour */}
        <Section title="AI Behaviour" icon={Bot} description="Control the tone and style of AI interactions">
          <div className="space-y-4">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Response tone</label>
              <select 
                className="input font-bold"
                value={company?.ai_config.tone || 'friendly and professional'}
                onChange={e => updateAI('tone', e.target.value)}
              >
                <option value="friendly and professional">Friendly and Professional</option>
                <option value="formal">Formal</option>
                <option value="casual">Casual</option>
                <option value="concise">Concise and Direct</option>
              </select>
            </div>
          </div>
        </Section>

        {/* Twilio Settings */}
        <Section title="Twilio Configuration" icon={Phone} description="Your outbound messaging details">
          <div className="space-y-4">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Twilio Phone Number</label>
              <input 
                className="input font-mono text-xs font-bold" 
                value={company?.twilio_phone_number || ''} 
                onChange={e => setCompany(c => c ? {...c, twilio_phone_number: e.target.value} : null)}
                placeholder="+1234567890"
              />
            </div>
          </div>
        </Section>

        {/* Save Bar */}
        <div className="sticky bottom-6 left-0 right-0 flex items-center justify-center z-20 px-4">
          <div className="card bg-white/90 backdrop-blur-md p-3 flex items-center gap-4 shadow-xl border-brand-100">
            <p className="text-[11px] text-gray-400 hidden sm:block font-bold italic">AI updates instantly on save.</p>
            <button 
              type="submit" 
              className="btn-primary px-10 py-2.5 shadow-lg shadow-brand-200 font-bold"
              disabled={saving}
            >
              {saving ? 'Saving...' : saved ? '✓ Settings Saved' : 'Save all changes'}
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
