"""fix_missing_columns

Revision ID: 2241ab9937ec
Revises: 3984c59cacc7
Create Date: 2026-03-12 20:57:37.213510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2241ab9937ec'
down_revision = '3984c59cacc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('nudge_interval_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'nudge_interval_days')
    # ### end Alembic commands ###