"""add_calcom_base_url_to_companies

Revision ID: 369b4590627d
Revises: 8bfe72b5879f
Create Date: 2026-03-12 22:44:14.783604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369b4590627d'
down_revision = '8bfe72b5879f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###