"""add_nudge_interval_to_leads

Revision ID: 3984c59cacc7
Revises: 656706908acd
Create Date: 2026-03-12 04:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3984c59cacc7'
down_revision: Union[str, None] = '656706908acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('nudge_interval_days', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'nudge_interval_days')
    # ### end Alembic commands ###
