"""make_sales_agent_id_optional

Revision ID: 656706908acd
Revises: 001_calcom_agent
Create Date: 2026-03-12 04:19:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656706908acd'
down_revision: Union[str, None] = '001_calcom_agent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'sales_agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'sales_agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
