"""add_manual_calendar_url_to_users

Revision ID: 8655ac80a088
Revises: 369b4590627d
Create Date: 2026-03-12 23:03:50.493425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8655ac80a088'
down_revision = '369b4590627d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('calcom_base_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'calcom_base_url')
    # ### end Alembic commands ###