"""add_managed_calendar_to_users

Revision ID: 8bfe72b5879f
Revises: 2241ab9937ec
Create Date: 2026-03-12 22:16:30.707383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe72b5879f'
down_revision = '2241ab9937ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendar_connected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('calcom_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('calcom_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('calcom_event_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'calendar_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendar_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'calcom_event_id')
    op.drop_column('users', 'calcom_username')
    op.drop_column('users', 'calcom_user_id')
    op.drop_column('users', 'calendar_connected')
    # ### end Alembic commands ###