"""add_company_id_to_messages

Revision ID: b00c8a1c7558
Revises: 8655ac80a088
Create Date: 2026-03-13 18:56:49.006853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00c8a1c7558'
down_revision = '8655ac80a088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###